Branch2
f7deleon/TrainingAndroid pull request #2
Opened 2018-06-21 20:01 UTC by f7deleon

Template

2018-06-21 20:09 UTC, mirland requested changes
Add a better pull request name, a better description and assign the reviewers

2018-06-21 20:10 UTC, mirland requested changes

2018-06-21 20:10 UTC, matir91 commented on docs/PULL_REQUEST_TEMPLATE.md
> +Short summary of your changes. Explain what have you done and comment the decisions that you may have taken.
change the file folder too

2018-06-22 13:49 UTC, FerrariBruno requested changes
Maybe you can add a basic `README.md` file, there are a ton of examples in the [Xmartlabs repos](https://github.com/xmartlabs). This is just for you to experience Markdown, it doesn't need to be a super README.

2018-06-22 13:57 UTC, FerrariBruno approved these changes

2018-06-22 14:13 UTC, mirland approved these changes
The name of the pull request is still wrong, rename it, you have to tell what are you doing

2018-06-22 14:17 UTC, merged