Added next and prev Buttons
f7deleon/TrainingAndroid pull request #4
Opened 2018-06-22 19:39 UTC by f7deleon

Added next and previous buttons and new question were introduced

### Related Trello cards:
https://trello.com/c/LfjGEJc4

2018-06-22 19:49 UTC, mirland requested changes

2018-06-22 19:49 UTC, matir91 commented on app/src/main/java/com/example/felipe/geoquiz/Question.kt
>  }
not needed

2018-06-22 19:49 UTC, matir91 commented on app/src/main/java/com/example/felipe/geoquiz/QuizActivity.kt
> +    private val questionBank = arrayOf(
move it to another class, maybe a controller

2018-06-22 19:49 UTC, matir91 commented on app/src/main/java/com/example/felipe/geoquiz/QuizActivity.kt
> +
rm * 2

2018-06-22 19:49 UTC, matir91 commented on app/src/main/java/com/example/felipe/geoquiz/QuizActivity.kt
> +    private fun printResult(message: Boolean) {
what do you think splitting this method in two: `checkAnswerResult` and `showAnswerResult`? The first one should call the controller

2018-06-22 19:49 UTC, matir91 commented on app/src/main/java/com/example/felipe/geoquiz/QuizActivity.kt
> +    private fun printResult(message: Boolean) {
The param name is not good

2018-06-22 19:49 UTC, matir91 commented on app/src/main/java/com/example/felipe/geoquiz/QuizActivity.kt
> +
rm

2018-06-25 13:12 UTC, FerrariBruno approved these changes

2018-06-25 13:34 UTC, merged

2018-06-25 13:42 UTC, matir91 commented on app/src/main/java/com/example/felipe/geoquiz/QuizController.kt
> +    public fun getQuestion(index: Int) = questionBank.get(index = index).textResId
the controller should not return the `reid`